[package]
name = "habit-tracker"
version = "0.1.0"
edition = "2024"


[dependencies]
assert_cmd = "2"
assert_fs = "1"
chrono = "0.4.35"
clap = { version = "4.0", features = ["derive"] }
predicates  = "3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.119"
