---
name: Build Rust binaries
on:
  push:
    tags:
      - 'v*'
env:
  BINARY_NAME: habit-tracker
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
          - target: aarch64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
          - target: x86_64-unknown-linux-gnu

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}
          override: true
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build project
        run: cross build --target ${{ matrix.target }} --release
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-${{ github.ref_name }}
          path: |
            target/${{ matrix.target }}/release/${{ env.BINARY_NAME }}
